### ISSUE TITLE
[name] issue in configuration.yaml

### ISSUE THREAD

**Issue by yieldhog** [daemondazz/homeassistant-displays#12]
Hi -- awesome add-on. I have it installed per instructions, it seems to be working for me, however, after I check my config I get the following error:

Invalid config for [display]: [name] is an invalid option for [display]. Check: display->name. (See /config/configuration.yaml, line 53). Please check the docs at https://home-assistant.io/components/display/

Running 0.94.4 -- thanks

My configuration.yaml section, line 53 is 'name' line. Thank you

display:
  - platform: fully_kiosk
    name: Kitchen Tablet
    host: 192.168.1.XX
    password: XXXXX

I've checked indentation etc, doesn't seem to be the issue.

**Comment by evdwaard** [comment]
I had the same - for me this seems to work:

Add into __init__.py in display folder:
```

DEFAULT_NAME = 'Fully Kiosk Browser'
DEFAULT_PORT = 2323

PLATFORM_SCHEMA = PLATFORM_SCHEMA.extend({
    vol.Optional(CONF_NAME, default=DEFAULT_NAME): cv.string,
    vol.Required(CONF_HOST): cv.string,
    vol.Optional(CONF_PORT, default=DEFAULT_PORT): cv.port,
    vol.Required(CONF_PASSWORD): cv.string
})

```

Adjust in the top of the file the required imports:
`
from homeassistant.const import (
    ATTR_ENTITY_ID,
    SERVICE_TURN_OFF, SERVICE_TURN_ON,
    STATE_ON,CONF_HOST,CONF_NAME,CONF_PASSWORD,CONF_PORT
)

`

**Comment by YoinkZed** [comment]
@evdwaard,
Can you share the complete init.py file?
I can't get it to work and I keep getting this error:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 33, in real_ip_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 67, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 216, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 115, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/core.py", line 31, in post
    errors = await async_check_ha_config_file(request.app['hass'])
  File "/usr/src/homeassistant/homeassistant/config.py", line 742, in async_check_ha_config_file
    res = await check_ha_config_file(hass)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/scripts/check_config.py", line 334, in check_ha_config_file
    hass, config, core_config.get(CONF_PACKAGES, {}), _pack_error)
  File "/usr/src/homeassistant/homeassistant/config.py", line 597, in merge_packages_config
    component = integration.get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 135, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/display/__init__.py", line 12, in <module>
    PLATFORM_SCHEMA = PLATFORM_SCHEMA.extend({
NameError: name 'PLATFORM_SCHEMA' is not defined

**Comment by daemondazz** [comment]
Thank you for your report. I've just upgraded my system from 0.92.2 to 0.95.4 and am unable to reproduce this error.

Can you please confirm how you installed the component? Also, that you are running the latest commit as the changes for the PLATFORM_SCHEMA configuration structure was made back in March.

**Comment by daemondazz** [comment]
Actually, scratch that, I missed you were running a check config for the errors to appear. I *can* reproduce that.

Let me have a look into it.

**Comment by daemondazz** [comment]
Ok, can you please try to pull the latest commit and let me know if that resolves the issue for you.

**Comment by yieldhog** [comment]
@daemondazz I made the changes suggested by @evdwaard and it fixed the issue on my system

**Comment by daemondazz** [comment]
The changes suggested by @evdwaard do not match the other components built-in to HA and tie the display component to the fully kiosk platform. Please try my latest update as this matches the other component structure.

**Comment by evdwaard** [comment]
@daemondazz thanks for making the fix properly! My changes were meant as a temp. workaround without really putting thought into it. :)

I'll check out your changes later this week.

**Comment by YoinkZed** [comment]
So I downloaded the init file and replaced the current, rebooted hassio and then reinserted the display component.

But unfortunately I get this error when running the configuration test:

> Package fully_kiosk setup failed. Component display cannot be merged. Expected a dict.
Code:
```
display:
  - platform: fully_kiosk
    name: '[Kitchen] Tablet'
    host: xxx.xxx.xxx.xxx
    password: !secret kiosk_remote_pwd
```

What did I do wrong (sorry)

**Comment by yieldhog** [comment]
@daemondazz I updated to your latest version and it appears to be working properly on my setup and passes config test. Thanks!
